# This file is part of nix-mineral (https://github.com/cynicsketch/nix-mineral/).
# Copyright (c) 2025 cynicsketch
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

{
  l,
  cfg,
  ...
}:

{
  imports = [
    (l.mkDeprecatedOptionModule [ "nix-mineral" "settings" "etc" "generic-machine-id" ] ''
      This option does not align with the current project scope and causes breakage with little benefit.

      If this option is set to false, simply remove the option from your
      configuration.

      If this option is set to true, add the following to your configuration
      if backwards compatibility is required:

      environment.etc.machine-id.text = "b08dfa6083e7567a1921a715000001fb";

      Otherwise, check for failed systemd services for secrets generated by
      systemd-creds and delete secrets dependent on the service so that they
      can be regenerated with the new machine-id.
    '')
  ];

  options = {
    generic-machine-id = l.mkDeprecatedOption ''
      Set machine-id to the Kicksecure machine-id, for privacy reasons.

      ::: {.warning}
      This may have unintended consequences if machine-id needs to be unique,
      e.g for log collection or VM management.
      :::
    '';
  };

  config = l.mkIf (cfg == true) {
    # /var/lib/dbus/machine-id doesn't exist on dbus enabled NixOS systems,
    # so we don't have to worry about that.
    environment.etc.machine-id.text = ''
      b08dfa6083e7567a1921a715000001fb
    '';
  };
}
