name: Mirror to Codeberg

on:
  push:
    branches:
    - '**'

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: mirror-repository
      uses: cynicsketch/mirror-action@v0.0.1
      with:
        REMOTE: 'ssh://git@codeberg.org/cynicsketch/nix-mineral.git'
        GIT_SSH_PRIVATE_KEY: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
        GIT_SSH_KNOWN_HOSTS: ${{ secrets.GIT_SSH_KNOWN_HOSTS }}
